const express = require("express");
const app = express();

const staffRoutes = require("./src/routes/staffRoutes");
const studentRoute = require("./src/routes/studentRoute");
const OrderRoutes = require("./src/routes/orderRoutes");
const PaymentRoutes = require("./src/routes/paymentRoutes");
const MasterRoutes = require("./src/routes/masterRoutes");
// const preCounsellingFormRoutes = require('./src/routes/preCounsellingFormRoutes');
const enrollementFormRoutes = require("./src/routes/enrollementFormRoutes");
const dashboardRoutes = require("./src/routes/dashboardRoutes");
const universityRoutes = require("./src/routes/universityRoutes");
const mockTestRoutes = require("./src/routes/mockTestRoutes");
const learningResourceRoutes = require("./src/routes/learningResourceRoutes");
const practiceAssignmentRoutes = require("./src/routes/practiceAssignmentRoutes");
const testRoutes = require("./src/routes/testRoutes");
const audioRoutes = require("./src/routes/audioRoutes");
const classRoutes = require("./src/routes/classRoutes");
const plannerRoutes = require("./src/routes/plannerRoutes");
const bannerRoutes = require("./src/routes/bannerRoutes");
const userAttendanceRoutes = require("./src/routes/userAttendanceRoutes");
const blogRoutes = require("./src/routes/blogRoutes");
const communityRoutes = require("./src/routes/communityRoutes");
const webBannerRoutes = require("./src/routes/webBannerRoutes");
const likeAndCommentsRoutes = require("./src/routes/likeAndCommentsRouter");
const personalCounsellorRoutes = require("./src/routes/personalConsellorRoutes");
const universitySortListingRoutes = require("./src/routes/universitySortListingRoutes");
const planRoutes = require("./src/routes/planRoutes");
const authRoutes = require("./src/routes/authRoutes");
const routeRoutes = require("./src/routes/routeRoutes");
const permissionRoutes = require("./src/routes/permissionRoutes");
const profileBuildingRoutes = require("./src/routes/profileBuildingRoutes");
const PyschometricRoutes = require("./src/routes/studyAbroadRoutes");
const DocumentManagementRoutes = require("./src/routes/documentManagementRoutes");
const StudentDocumentManagementRoutes = require("./src/routes/studentDocumentManagementRoutes");
const studentPersonalCounsellorLogRoutes = require("./src/routes/studentPersonalCounsellorLogsRoutes");
const psychometricTestRoutes = require("./src/routes/psychometricTestRoutes");
const resourcesRoutes = require("./src/routes/resourcesRoutes");
const postEnrollmentSupportRoutes = require("./src/routes/postEnrollmentSupport");
const eventRoutes = require("./src/routes/eventRoutes");
const testimonialRoutes = require("./src/routes/testimonialRoutes");
const regulatoryBodiesRoutes = require("./src/routes/regulatoryRoutes");
const batchRoutes = require("./src/routes/batchRoutes");
const immersionCountriesRoutes = require("./src/routes/immersionRoutes");
const indianUniversitiesRoutes = require("./src/routes/indianUniversityRoutes");
const studyAbroadUniversitiesRoutes = require("./src/routes/studyAbroadRoute");
const admissionServiceRoutes = require("./src/routes/admissionServiceRoutes");
const examStatusRoutes = require("./src/routes/examStatusRoutes");

app.use("/staff", staffRoutes);
app.use("/student", studentRoute);
app.use("/order", OrderRoutes);
app.use("/payment", PaymentRoutes);
app.use("/master", MasterRoutes);
// app.use("/preCounsellingForm", preCounsellingFormRoutes);
app.use("/enrollementForm", enrollementFormRoutes);
app.use("/dashboard", dashboardRoutes);
app.use("/university", universityRoutes);
app.use("/mockTest", mockTestRoutes);
app.use("/learningResource", learningResourceRoutes);
app.use("/test", testRoutes);
app.use("/audio", audioRoutes);
app.use("/class", classRoutes);
app.use("/planner", plannerRoutes);
app.use("/banner", bannerRoutes);
app.use("/userAttendance", userAttendanceRoutes);
app.use("/practiceAssignment", practiceAssignmentRoutes);
app.use("/blogs", blogRoutes);
app.use("/community", communityRoutes);
app.use("/community/likeAndComments", likeAndCommentsRoutes);
app.use("/web-banner", webBannerRoutes);
app.use("/personal-counsellor", personalCounsellorRoutes);
app.use("/university-sort-listing", universitySortListingRoutes);
app.use("/plan", planRoutes);
app.use("/auth", authRoutes);
app.use("/route", routeRoutes);
app.use("/permission", permissionRoutes);
app.use("/profile-building", profileBuildingRoutes);
app.use("/study-aboard", PyschometricRoutes);
app.use("/document-management", DocumentManagementRoutes);
app.use("/student-document-management", StudentDocumentManagementRoutes);
app.use("/student-personal-counsellor-log", studentPersonalCounsellorLogRoutes);
app.use("/psychometricTest", psychometricTestRoutes);
app.use("/resources", resourcesRoutes);
app.use("/post-enrollment-support", postEnrollmentSupportRoutes);
app.use("/event", eventRoutes);
app.use("/testimonial", testimonialRoutes);
app.use("/regulatory-bodies", regulatoryBodiesRoutes);
app.use("/batch", batchRoutes);
app.use("/immersion-countries", immersionCountriesRoutes);
app.use("/indian-universities", indianUniversitiesRoutes);
app.use("/study-abroad-universities", studyAbroadUniversitiesRoutes);
app.use("/admission-service", admissionServiceRoutes);
app.use("/exam-status", examStatusRoutes);

module.exports = app;
