exports.Messages = {
  UNAUTHORIZED: "Unauthorized access",
  STAFF_LOGIN: "staff login successfully",
  STUDENT_LOGIN: "student login successfully",
  STAFF_CREATED: "staff created successfully",
  DATA_CREATED: "Data created successfully",
  DATA_DELETED: "Data deleted successfully",
  STAFF_DELETE: "staff deleted successfully",
  STAFF_UPDATE: "staff updated successfully",
  STAFF_NOT_FOUND: "staff not found",
  USER_NOT_FOUND: "User not found",
  STUDENT_NOT_FOUND: "student not found",
  DATA_UPDATE: "Data updated successfully",
  DATA_RETRIVED: "data retrieved successfully",
  INTERNAL_ERROR: "internal server problem",
  INVALID_ID: "ID invalid.",
  INVALID_EMAIL: "Email invalid.",
  INVALID_PASSWORD: "Password invalid.",
  INVALID_OTP: "Invalid OTP",
  EMAIL_EXISTS: "The email already exists.",
  MOBILE_EXISTS: "Mobile number already exists.",
  MOBILE_REQUIRED: "The mobile number required.",
  DATA_NOT_FOUND: "data not found",
  DATA_FETCHED: "Data fetch successfully",
  PLAN_NOT_MATCH: "Plan does not exists",
  OTP_SEND: "OTP send successfully",
  OTP_VERIFIED: "OTP verified successfully",
  MOBILE_NOT_EXISTS: "Mobile number not exists",
  PASSWORD_RESET_SUCCESSFULLY: "Password reset successfully",
  PASSWORD_DOES_NOT_MATCH: "Password not matched",
  DUPLICATE_DATA: "Data with same name exists",
  DUPLICATE_DATA_US: "University and course combination has already been added",
  SEND_DUPLICATE_DATA: "You send duplicate data.Please check",
  TUTION_FEE: "Tution fee not more than 50000 Dollar",
  COUNTRY_NOT_FOUND: "Country not found",
  INVALID_COURSE: "Invalid course found",
  UNIVERSITY_NOT_FOUND: "University not found",
  INVALID_STATE_FORMAT: "Incorrect Formate",
  INVALID_STATE: "Given state not belong given country",
  TEST_NOT_FOUND: "Test not found",
  ANSWERS_CHECKED: "Answers Checked",
  CLASS_NOT_FOUND: "Class not found",
  CLASS_JOINED: "Class joined",
  UPLOAD_DONE: "Upload Completed",
  SAME_COURSE: "Same course exists",
  DATA_NOT_PROVIDED: "Data not provided, please provide data",
  ATTENDANCE_MARKED_SUCCESSFULLY: "Attendance marked successfully",
  ATTENDANCE_UPDATE_SUCCESSFULLY: "Attendance update successfully",
  SCHEDULED: "Meeting Scheduled",
  MAX_CLASS_REACHED: "You can reached your maximun class limit",
  MOBILE_EMAIL_EXISTS: "Phone or Email already exists",
  FORM_SUBMIT: "Form submit successfully",
  MEETING_SCHEDULED: "Your meeting scheduled",
  REQUIRED_FIELDS: "Please provide required fields",
  SLUG_ALREADY_EXISTS: "Blog already exists with provided slug url",
  ID_PARAMETER_REQUIRED: "Id parameter required",
  INVALID_SLUG_URL:
    "Invalid slugUrl. Only alphanumeric characters, dashes, and underscores are allowed.",
  INVALID_DATE: "Invalid date",
  DUPLICATE_EMAIL_OR_PHONE: "Duplicate Email or phone",
  INVALID_PLAN: "No valid plans found",
  INVALID_TYPE: "Invalid user type",
  PASSWORD_UPDATED: "Password Updated Successfully",
  DUPLICATE_TITLE: "Data with the same title already exists.",
  INVALID_ROUTE_ID: "Route id invalid",
  INVALID_ROLE_ID: "Role id invalid",
  PERMISSION_CREATED: "Permission Created Successfully",
  INVALID_INPUT: "Input data invalid",
  MEETING_NOT_FOUND: "Meeting not found",
  INVALID_BASE64: "PDF must be a valid base64-encoded string.",
  INVALID_DOC_CATEGORY: "No valid document category provided",
  INVALID_FORMAT: "Invalid document format",
  DOCUMENT_MANAGEMENT_ALREADY_EXISTS:
    "Document management data already exists for one or more of these students.",
  STUDENT_DOCUMENT_MANAGEMENT_NOT_CREATED_YET:
    "Documents yet to be upload by student",
  DOCUMENT_NOT_FOUND: "Document not found",
  FAILED_TO_CREATE_LOG: "Failed To Create Student Log",
  COMMUNTIY_CREATED: "Community created successfully.",
  COMMUNTIY_DELETED: "Community deleted successfully!",
  COMMUNTIY_UPDATE: "Community updated successfully.",
  REQUIRED_FIELD: (field) => `${field} required.`,
  STUDENT_NOT_FOUND_BY_ID: (id) => `Student with ID ${id} not found.`,
  INVALID_BASE64_IMAGE: "Image must be a valid base64-encoded string. ",

  OTP_ALREADY_VERIFIED:
    "This OTP has already been verified. Please request a new OTP if needed.",
  OTP_EXPIRED: "The OTP has expired. Please request a new one to continue.",
  LOG_ALREADY_CREATED: (cutoffTime) =>
    `Log already created. You can create a new log after ${new Date(
      cutoffTime
    ).toLocaleString()}.`,

  // Dynamic messages
  NOT_FOUND_DATA: (data) => `${data} not found.`,
  CREATED_DATA: (data) => `${data} created successfully.`,
  DELETED_DATA: (data) => `${data} deleted successfully.`,
  UPDATED_DATA: (data) => `${data} updated successfully.`,

  // SECTION - Counsellor
  COUNSELLOR_NOT_FOUND: "No Counsellor Assigned to this student.",
  AMOUNT_ERROR: "Amount should be greater then 0.",

  SAME_BATCH: "Batch already exists.",

  SHORTLISTED: "University shortlisted successfully",
};
